export const SET_MICRO = 'SET_MICRO'
export const SET_TOKEN = 'SET_TOKEN'
export const SET_USET_ID = 'SET_USER_ID'
export const SET_PERMISSIONS = 'SET_PERMISSIONS'
export const SET_ROLES = 'SET_ROLES'
export const SET_ROUTERS = 'SET_ROUTERS'
export const SET_FLATTEN_ROUTERS = 'SET_FLATTEN_ROUTERS'
